### ISSUE TITLE
Session Stats,  incorrect profit/ 1h&24h value when bot stop and resume.

### ISSUE THREAD

**Issue by PMalfG** [Seuntjie900/DoormatBot#6]
![image](https://user-images.githubusercontent.com/48416229/82113619-bb630880-9757-11ea-9833-194d0a591a38.png)

Profit / hours and Profit / 24 hours are wrong, i think it's happend when i stoped and resumed script,before that there was no problem.
Luck value is always equal to 0

**Comment by Seuntjie900** [comment]
Session stats isn't taking the timerunning value into account when calculating the timespan, needs to be amended

**Comment by Seuntjie900** [comment]
298dda56febcbb0d4a5ab02fbe474008d393e1a1
